#!/bin/bash
name="$1"
lower="$2"

root="app/${name}"
# name but first char to lowercase/

echo "scaffolding ${name}";

cp -r tools/scaffold $root;

sed -i "s/Blog/${name}/g" "${root}/BlogServiceProvider.php"
sed -i "s/blog/${lower}/g" "${root}/BlogServiceProvider.php"

sed -i "s/Blog/${name}/g" "${root}/Http/routes.php"
sed -i "s/blog/${lower}/g" "${root}/Http/routes.php"

sed -i "s/Blog/${name}/g" "${root}/Http/breadcrumbs.php"
sed -i "s/blog/${lower}/g" "${root}/Http/breadcrumbs.php"

sed -i "s/Blog/${name}/g" "${root}/resources/assets/js/admin/config.js"
sed -i "s/blog/${lower}/g" "${root}/resources/assets/js/admin/config.js"

sed -i "s/Blog/${name}/g" "${root}/resources/assets/js/admin/models.js"
sed -i "s/blog/${lower}/g" "${root}/resources/assets/js/admin/models.js"

sed -i "s/Blog/${name}/g" "${root}/resources/assets/js/admin/translations.js"
sed -i "s/blog/${lower}/g" "${root}/resources/assets/js/admin/translations.js"

mv "${root}/BlogServiceProvider.php" "${root}/${name}ServiceProvider.php"
mv "${root}/config/blog.php" "${root}/config/${lower}.php"